/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SpectreAnimation, } from "./components/helpers/app-animate/app-animate";
export namespace Components {
    interface AppAnimate {
        "animations": SpectreAnimation[];
    }
    interface AppMain {
    }
    interface AppRoot {
    }
    interface PageLogin {
    }
}
declare global {
    interface HTMLAppAnimateElement extends Components.AppAnimate, HTMLStencilElement {
    }
    var HTMLAppAnimateElement: {
        prototype: HTMLAppAnimateElement;
        new (): HTMLAppAnimateElement;
    };
    interface HTMLAppMainElement extends Components.AppMain, HTMLStencilElement {
    }
    var HTMLAppMainElement: {
        prototype: HTMLAppMainElement;
        new (): HTMLAppMainElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageLoginElement extends Components.PageLogin, HTMLStencilElement {
    }
    var HTMLPageLoginElement: {
        prototype: HTMLPageLoginElement;
        new (): HTMLPageLoginElement;
    };
    interface HTMLElementTagNameMap {
        "app-animate": HTMLAppAnimateElement;
        "app-main": HTMLAppMainElement;
        "app-root": HTMLAppRootElement;
        "page-login": HTMLPageLoginElement;
    }
}
declare namespace LocalJSX {
    interface AppAnimate {
        "animations"?: SpectreAnimation[];
    }
    interface AppMain {
    }
    interface AppRoot {
    }
    interface PageLogin {
    }
    interface IntrinsicElements {
        "app-animate": AppAnimate;
        "app-main": AppMain;
        "app-root": AppRoot;
        "page-login": PageLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-animate": LocalJSX.AppAnimate & JSXBase.HTMLAttributes<HTMLAppAnimateElement>;
            "app-main": LocalJSX.AppMain & JSXBase.HTMLAttributes<HTMLAppMainElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-login": LocalJSX.PageLogin & JSXBase.HTMLAttributes<HTMLPageLoginElement>;
        }
    }
}
